name: Build & Publish Docs with Sphinx

on:
  release:
    types: [published]


jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies & Generate documentation
      run: |
        python -m pip install --upgrade pip
        python setup.py develop
        pip install -r requirements.txt
        pip install jupyter nbconvert nbformat sphinx
        jupyter nbconvert --to rst --output ../docs/README.rst examples/quickstart.ipynb

    - name: Move README.rst & Build sphinx documentation
      run: |
        cd docs
        sphinx-apidoc --separate -f -o source/ ../src/skmixed
        make clean
        make html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/build/_html # The folder the action should deploy.